service: sls-offline

provider:
  name: aws
  runtime: nodejs8.10

plugins:
  - serverless-offline
  - serverless-mocha-plugin

functions:
  hello2:
    handler: handler2
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get
