'use strict';

// tests for hello
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('hello', '/handler.js', 'hello');

describe('hello', () => {
  before(done => {
    done();
  });

  it('implement tests here', async () => {
    const response = await wrapped.run({ body: { val1: 2, val2: 3 } });
    expect(response.body).to.eq(5);
  });
});
