'use strict';

// tests for hello
// Generated by serverless-mocha-plugin

const mochaPlugin = require('serverless-mocha-plugin');
const expect = mochaPlugin.chai.expect;
let wrapped = mochaPlugin.getWrapper('hello', '/handler.js', 'hello');

describe('hello', () => {
  before(done => {
    done();
  });

  it('should 1 + 1 = "2"', () => {
    return wrapped
      .run({ queryStringParameters: { v1: 1, v2: 1 } })
      .then(response => {
        expect(response.body).to.eq('2');
      });
  });
});
